### ISSUE TITLE
Linear section layout

### ISSUE THREAD

**Issue by TonicArtos** [TonicArtos/SuperSLiM#190]
A section layout manager that lays out items as a linear list.

**Tasks**
- [x] At top
- [x] Layout
- [x] Fill top
- [x] Fill bottom
- [x] Trim top
- [x] Trim bottom

**Validation**
- [x] On scroll to top, child fills top by dy.
- [x] On scroll to bottom, child fills bottom by dy.
- [x] Disappeared/ignored height set properly.
- [x] Removed height set properly.
- [ ] State is persisted
