### ISSUE TITLE
Prepare milestone 5 release

### ISSUE THREAD

**Issue by TonicArtos** [TonicArtos/SuperSLiM#217]
There are a few things to be done before the milestone can be pushed out.

- [ ] tonicartos.com -> tonicartos.nz
- [ ] Clean up build
- [ ] Make new master branch on version5 and switch default branch over
- [ ] Update gradle for pushing to maven
- [ ] Push to maven
- [ ] Upload release to GitHub
